### ISSUE TITLE
audit function fails for concurrent map writes

### ISSUE THREAD

**Issue by davidebianchi** [rond-authz/rond#418]
#### Describe the bug

audit function fails for concurrent map writes and causes a crash of the service

#### Expected behavior

Audit works correctly without crash the service

#### Replication info

- Rönd version: v1.14.0
- Running mode: sidecar

#### Additional context

Stack trace:

<details><summary>Details</summary>
<p>

```txt
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 77598 [running]:
github.com/rond-authz/rond/internal/audit.(*SingleRecordCache).Store(0xc00051e3d8, 0xc000617100?)
	/app/internal/audit/cache.go:34 +0xf3
github.com/rond-authz/rond/internal/audit.init.func1({{0x13218c8, 0xc00073a660}, {0x1327750, 0xc000299260}, {0x1319d80, 0xc0000540e0}, 0xc00073aa20, {0x131dd48, 0xc000c8a97c}, 0x0, ...}, ...)
	/app/internal/audit/rego_builtin.go:51 +0xc2
github.com/rond-authz/rond/internal/audit.init.Function1.func2.1()
...
```

</p>
</details>

**Comment by fredmaggiowski** [comment]
To fix the crash we should:

- use a sync.Map or place a mutex/rwlock in the `internal/audit/cache.go#SingleRecordCache` impl
- implement an way to preserve all unique values when the same key is supplied by multiple policies

Morever we should understand whether a chan or routine pool may be required to prevent performance bottlenecks in policy execution (i'd prefer a chan + audit routine that collects data but we should carefully think about this)

**Comment by davidebianchi** [comment]
Nope, I went deeper in this issue and it could be easily fixed adding a pool of audit agent. The sync.Map would prevent the specific error, but there could be some data which are overwritten during parallel execution between write and read.

The problem is that the `SingleRecordCache` is reused in all policies execution, and instanciated only in the `NewFromOas` or `NewFromConfig` function. Instead, we should create a pool of agent and at each evaluation create a new agent which inherited the global labels and create a new cache.
